version: '3.8'

services:
  db:
    image: postgres:14
    container_name: hw02_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: hw02_fastapi
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:

